# Starter pipeline
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Pay-As-You-Go(8853d54c-c00e-4562-b764-60ec3da433ab)'
    subscriptionId: '8853d54c-c00e-4562-b764-60ec3da433ab'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'NetworkWatcherRG'
    location: 'Canada Central'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/abhidit/LinkedTemplate/main/main.json'
    deploymentMode: 'Incremental'
    deploymentName: 'f1'
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
